version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/employee_rating_codeDeploy

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 20
      runas: ec2-user
  ApplicationStart:
    - location: start.sh
      timeout: 20
      runas: ec2-user